# Generated by Django 3.2.8 on 2021-10-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complectation',
            name='mark_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='cars.markmodel'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='complectation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='cars.complectation'),
        ),
        migrations.AlterField(
            model_name='markmodel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_models', to='cars.year'),
        ),
        migrations.AlterField(
            model_name='subdetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_details', to='cars.detail'),
        ),
        migrations.AlterField(
            model_name='year',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='cars.mark'),
        ),
    ]
