# Generated by Django 3.2.8 on 2021-10-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211013_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('price', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Out of stock', 'Ofs'), ('In stock', 'Is')], default='In stock', max_length=16)),
                ('sub_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cars.subdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PartVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('price', models.FloatField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='cars.part')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='marks', to='cars.Country'),
        ),
        migrations.AddField(
            model_name='year',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='years', to='cars.Country'),
        ),
    ]
