# Generated by Django 3.2.8 on 2021-10-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211025_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('Out of stock', 'Ofs'), ('In stock', 'Is')], default='In stock', max_length=16),
        ),
    ]
