# Generated by Django 3.2.8 on 2021-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_part_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='part_images'),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('Out of stock', 'Oos'), ('In stock', 'Is')], default='In stock', max_length=16),
        ),
    ]
